- name: Install Dnsmasq
  yum:
    pkg: dnsmasq
    state: present
  tags: dnsmasq

- name: Set configuration file
  template:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
  tags: dnsmasq

- name: Apache | add apache iptable rule
  command: /sbin/iptables -I INPUT -p udp -m udp --dport 53 -j ACCEPT 
  sudo: true

- name: save iptables
  command: iptables-save
  sudo: true

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: dnsmasq
