- name: Install ose
  yum:
    pkg: ansible
    state: present
  tags: ose

- name: Set configuration file
  template:
    src: hosts.j2
    dest: /etc/ansible/hosts
  tags: ose

- name: 
## https://github.com/openshift/openshift-ansible/issues/1750
git clone https://github.com/openshift/openshift-ansible.git
export ANSIBLE_FILTER_PLUGINS=openshift-ansible/filter_plugins
export ANSIBLE_LOOKUP_PLUGINS=openshift-ansible/lookup_plugins 



### # added this to opens the dns port 
## /usr/share/ansible/openshift-ansible/roles/haproxy/defaults/main.yml

- service: apache port
  port: "80/tcp"



#passwd -c -b  temp demo  demo
#- name: execute install ose ansible playbook
#  command: ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
#  sudo: true

#- name: Make sure Dnsmasq is running
#  service:
#    name: atomic-openshift-master
#    state: started
#    enabled: yes
#  tags: ose
